$ANSIBLE_VAULT;1.1;AES256
36386666633033393532643462353338353838363238303862343939326333343534353666316337
6639393232376232386239636339323663636338376337640a306464333638326438326632316264
37646137396366353633336533326635656365643337636432306337616235303037313633303333
6533323734623134310a653530393363383137333938373561393165343237666233623933303636
34373136663666316331643536346234653266373433623236653362393733643865
