all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 192.168.1.101
          ansible_user: kirill
          ansible_ssh_private_key_file: /Users/kirylputseyeu/.ssh/server.key
    databases:
      hosts:
        db01:
          ansible_host: 192.168.1.137
          ansible_user: kirill
          ansible_ssh_private_key_file: /Users/kirylputseyeu/.ssh/server.key

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
