$ANSIBLE_VAULT;1.1;AES256
66663231313163663035393861613634626162363165343034666466636233643238653533663237
6230343761393938333264343131663534356636386333320a643036653331383137303637353261
39643630343631373166343338663265386134623738376261636265636233386239363539326264
3964626461393966390a663232666265393138633437313137333634326230393663386566376232
37363464353836383661316339386166353663623334306461663266633039616263
